name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List File
        run: |
          pwd
          ls
      - name: Simple js Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: James
      - name: Log Greet Times
        run: echo "${{ steps.greet.outputs.time }}"